# Generated by Django 5.2.9 on 2025-12-24 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Manager", "Manager"), ("Team_Member", "Team_Member")],
                max_length=20,
                null=True,
            ),
        ),
    ]
