# Generated by Django 5.2.9 on 2025-12-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_alter_user_password_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
